### ISSUE TITLE
Can not connect to SMTP without credentials

### ISSUE THREAD

**Issue by wilcoschoneveld** [Unleash/unleash#1583]
### Describe the bug

Our SMTP server does not require a username and password, but when leaving the fields blank the unleash email service tries to connect to smtp like this: `smtp://undefined:undefined@host:port`

### Steps to reproduce the bug

```
unleash
  .start({
    email: {
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      sender: process.env.EMAIL_SENDER
    }
  })
  .then((unleash) => {
    console.log(
      `Unleash started on port ${unleash.app.get('port')}`,
    );
  });
```

### Expected behavior

Unleash email service should connect to `smtp://host:port`

### Screenshots

```
[2022-05-10T11:02:51.445] [INFO] services/email-service.ts - Initialized transport to XXX.XXX.XXX.XXX on port 25 with user: undefined

[2022-05-10T12:08:00.079] [WARN] services/email-service.ts - Failed to send getting started email Error: Connection timeout
    at SMTPConnection._formatError (/Users/251743/Documents/helios-unleash/node_modules/nodemailer/lib/smtp-connection/index.js:784:19)
    at SMTPConnection._onError (/Users/251743/Documents/helios-unleash/node_modules/nodemailer/lib/smtp-connection/index.js:770:20)
    at Timeout.<anonymous> (/Users/251743/Documents/helios-unleash/node_modules/nodemailer/lib/smtp-connection/index.js:229:22)
    at listOnTimeout (node:internal/timers:557:17)
    at processTimers (node:internal/timers:500:7) {
  code: 'ETIMEDOUT',
  command: 'CONN'
}
```

### Unleash version

4.9.1

### Subscription type

Open source

### Hosting type

Self-hosted

**Comment by wilcoschoneveld** [comment]
Workaround:

```
unleash
  .start({
    email: {
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      sender: process.env.EMAIL_SENDER
    }
  })
  .then((unleash) => {
    unleash.services.emailService.mailer = nodemailer.createTransport({
      host: process.env.EMAIL_HOST,
      port: process.env.EMAIL_PORT,
      secure: false,
      tls: {
        rejectUnauthorized: false
      }
    });

    console.log(
      `Unleash started on port ${unleash.app.get('port')}`,
    );
  });
```

**Comment by thomasheartman** [comment]
Hey, @wilcoschoneveld! Thanks for raising this and thanks for also providing a fix 🙌🏼  From what I can tell, everything seems pretty reasonable, but I've raised this with the team so that someone whose more knowledgeable about the email parts of Unleash can have a look at it. We should get back to you with an update some time tomorrow at latest ☺️

**Comment by chriswk** [comment]
Hi @wilcoschoneveld . Appreciate you taking the time to make both the issue and the PR. Your PR seems very reasonable, so I'll update the PR with my review and we'll move on from there. Thank you!. :)
