### ISSUE TITLE
Unable to import the feature flags from another installation if features use tags

### ISSUE THREAD

**Issue by uthark** [Unleash/unleash#3662]
### Describe the bug

Unleash fails on importing JSON from another instance.

### Steps to reproduce the bug

1. Have 2 unleash instances running the same version.
2. Export configuration on first unleash version.
3. Import configuration on the second unleash version

### Expected behavior

Import works

### Logs, error output, etc.

```bash
unleash-5d765c58db-ff8br unleash [2023-05-02T01:06:31.095] [ERROR] controller/ExportImportController - Server failed executing request error: insert into "tags" ("type", "value") values ($1, $2) - duplicate key value violates unique constraint "tags_pkey"
unleash-5d765c58db-ff8br unleash     at Object.queryBuilder (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:111:26)
unleash-5d765c58db-ff8br unleash     at createQueryBuilder (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:315:26)
unleash-5d765c58db-ff8br unleash     at TagStore.knex [as db] (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:100:12)
unleash-5d765c58db-ff8br unleash     at TagStore.createTag (/unleash/node_modules/unleash-server/dist/lib/db/tag-store.js:53:20)
unleash-5d765c58db-ff8br unleash     at FeatureTagService.createTagIfNeeded (/unleash/node_modules/unleash-server/dist/lib/services/feature-tag-service.js:72:37)
unleash-5d765c58db-ff8br unleash     at runMicrotasks (<anonymous>)
unleash-5d765c58db-ff8br unleash     at processTicksAndRejections (node:internal/process/task_queues:96:5)
unleash-5d765c58db-ff8br unleash     at async FeatureTagService.addTag (/unleash/node_modules/unleash-server/dist/lib/services/feature-tag-service.js:24:9)
unleash-5d765c58db-ff8br unleash     at async Promise.all (index 1)
unleash-5d765c58db-ff8br unleash     at async ExportImportService.import (/unleash/node_modules/unleash-server/dist/lib/features/export-import-toggles/export-import-service.js:65:9) {
unleash-5d765c58db-ff8br unleash   length: 200,
unleash-5d765c58db-ff8br unleash   severity: 'ERROR',
unleash-5d765c58db-ff8br unleash   code: '23505',
unleash-5d765c58db-ff8br unleash   detail: 'Key (type, value)=(simple, billing) already exists.',
unleash-5d765c58db-ff8br unleash   hint: undefined,
unleash-5d765c58db-ff8br unleash   position: undefined,
unleash-5d765c58db-ff8br unleash   internalPosition: undefined,
unleash-5d765c58db-ff8br unleash   internalQuery: undefined,
unleash-5d765c58db-ff8br unleash   where: undefined,
unleash-5d765c58db-ff8br unleash   schema: 'public',
unleash-5d765c58db-ff8br unleash   table: 'tags',
unleash-5d765c58db-ff8br unleash   column: undefined,
unleash-5d765c58db-ff8br unleash   dataType: undefined,
unleash-5d765c58db-ff8br unleash   constraint: 'tags_pkey',
unleash-5d765c58db-ff8br unleash   file: 'nbtinsert.c',
unleash-5d765c58db-ff8br unleash   line: '670',
unleash-5d765c58db-ff8br unleash   routine: '_bt_check_unique',
unleash-5d765c58db-ff8br unleash   originalStack: 'error: insert into "tags" ("type", "value") values ($1, $2) - duplicate key value violates unique constraint "tags_pkey"\n' +
unleash-5d765c58db-ff8br unleash     '    at Parser.parseErrorMessage (/unleash/node_modules/pg-protocol/dist/parser.js:287:98)\n' +
unleash-5d765c58db-ff8br unleash     '    at Parser.handlePacket (/unleash/node_modules/pg-protocol/dist/parser.js:126:29)\n' +
unleash-5d765c58db-ff8br unleash     '    at Parser.parse (/unleash/node_modules/pg-protocol/dist/parser.js:39:38)\n' +
unleash-5d765c58db-ff8br unleash     '    at TLSSocket.<anonymous> (/unleash/node_modules/pg-protocol/dist/index.js:11:42)\n' +
unleash-5d765c58db-ff8br unleash     '    at TLSSocket.emit (node:events:513:28)\n' +
unleash-5d765c58db-ff8br unleash     '    at addChunk (node:internal/streams/readable:315:12)\n' +
unleash-5d765c58db-ff8br unleash     '    at readableAddChunk (node:internal/streams/readable:289:9)\n' +
unleash-5d765c58db-ff8br unleash     '    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)\n' +
unleash-5d765c58db-ff8br unleash     '    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)',
unleash-5d765c58db-ff8br unleash   isJoi: true
```
```


### Screenshots

_No response_

### Additional context

Feature tags block looks like this:

```
    "featureTags": [
        {
            "featureName": "feature1",
            "tagType": "simple",
            "tagValue": "billing"
        },
        {
            "featureName": "feature2",
            "tagType": "simple",
            "tagValue": "billing"
        },
       

    ],
```

If I remove the tags, import works as expected.


### Unleash version

4.22

### Subscription type

Open source

### Hosting type

Self-hosted

### SDK information (language and version)

_No response_

**Comment by sjaanus** [comment]
@uthark thank you for reporting this bug. I will assign it to the relevant team to get it fixed.
