### ISSUE TITLE
🟢 Support noop writes during maintenance mode

### ISSUE THREAD

**Issue by cinnes** [Unleash/unleash#3760]
### Describe the feature request

I would like unleash to be operable connected to a read only replica db in the event of disaster recovery.

### Background

When encountering a disaster, we fall back to a read replica database whilst recovering to prevent total downtime, write operations are not possible. When connecting to the db under a read only user, unleash will immediately crash with the following stack trace:

```
2023-05-12 12:08:36 [ERROR] error: delete from "client_instances" where created_at < now() - interval '2 days' - permission denied for table client_instances
2023-05-12 12:08:36     at createQueryBuilder (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:313:26)
2023-05-12 12:08:36     at ClientInstanceStore.knex [as db] (/unleash/node_modules/knex/lib/knex-builder/make-knex.js:100:12)
2023-05-12 12:08:36     at ClientInstanceStore._removeInstancesOlderThanTwoDays (/unleash/node_modules/unleash-server/dist/lib/db/client-instance-store.js:44:33)
2023-05-12 12:08:36     at Timeout.clearer [as _onTimeout] (/unleash/node_modules/unleash-server/dist/lib/db/client-instance-store.js:39:36)
2023-05-12 12:08:36     at listOnTimeout (internal/timers.js:557:17)
2023-05-12 12:08:36     at processTimers (internal/timers.js:500:7)
```

See discussion in [this](https://unleash-community.slack.com/archives/CGP2MCHPF/p1683891020901819) slack thread.

### Solution suggestions

If there are no more non-essential writes, make timers noop during maintenance mode. Otherwise, could potentially make writes soft fail to continue to allow reads?

**Comment by sjaanus** [comment]
Thank you for submitting this feature request @cinnes. We greatly appreciate your input and have promptly forwarded it to the appropriate team. This will be prioritized once they have the necessary resources available.

**Comment by kwasniew** [comment]
@cinnes This PR (https://github.com/Unleash/unleash/pull/3854) will stop the scheduler from running in the maintenance mode. There's still one DB table where we need the DELETE/UPDATE privileges. It's the unleash_session from connect-session-knex that stores your user session. 

When I granted those permissions on one table:
GRANT DELETE ON unleash_session TO readonly;
GRANT UPDATE ON unleash_session TO readonly;

then all the other operations worked fine in the maintenance mode.

**Comment by ivarconr** [comment]
I consider this task to be done. Unleash will now be able to run in read-only mode when maintenance mode is enabled. If sessions are backed with postgres (on by default) users will not be able to log in (but connected SDKs will still be able to fetch data). 

We could consider to expose the [session option](https://github.com/Unleash/unleash/blob/main/src/lib/types/option.ts#L38) to not store sessions in the database. The problem with using this option is that Unleash will only carry session data in memory, meaning it will not work well for users if there are multiple instances of Unleash and no sticky guarantees in the LB.
