### ISSUE TITLE
getting password authentication error even though password is correct with nodeV8.15.0

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#377]
2019-01-23 10:33:11[ERROR] error: password authentication failed for user "x_y"
https://github.com/Unleash/unleash/issues/376y"
"5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Connection.parseE (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:555:11)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Connection.parseMessage (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:380:19)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.<anonymous> (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:120:22)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at emitOne (events.js:116:13)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.emit (events.js:211:7)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at addChunk (_stream_readable.js:263:12)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at readableAddChunk (_stream_readable.js:250:11)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.Readable.push (_stream_readable.js:208:10)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at TCP.onread (net.js:601:20)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 detail: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 hint: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 position: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 internalPosition: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 internalQuery: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 where: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 schema: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 table: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 column: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 dataType: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 constraint: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 file: 'auth.c',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 line: '288',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 routine: 'auth_failed' },5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 isOperational: true,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 length: 101,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 severity: 'FATAL',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 code: '28P01',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 detail: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 hint: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 position: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 internalPosition: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 internalQuery: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 where: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 schema: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 table: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 column: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 dataType: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 constraint: undefined,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 file: 'auth.c',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 line: '288',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 routine: 'auth_failed' }5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11[91m[2019-01-23T09:33:11.757] [ERROR] server-impl.js - [39mFailed to migrate db { error: password authentication failed for user "x_y
"5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Connection.parseE (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:555:11)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Connection.parseMessage (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:380:19)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.<anonymous> (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:120:22)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at emitOne (events.js:116:13)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.emit (events.js:211:7)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at addChunk (_stream_readable.js:263:12)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at readableAddChunk (_stream_readable.js:250:11)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.Readable.push (_stream_readable.js:208:10)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at TCP.onread (net.js:601:20)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 cause: 5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 { error: password authentication failed for user "x_y
"5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Connection.parseE (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:555:11)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Connection.parseMessage (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:380:19)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.<anonymous> (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:120:22)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at emitOne (events.js:116:13)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.emit (events.js:211:7)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at addChunk (_stream_readable.js:263:12)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at readableAddChunk (_stream_readable.js:250:11)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at Socket.Readable.push (_stream_readable.js:208:10)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 at TCP.onread (net.js:601:20)5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 name: 'error',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 length: 101,5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 severity: 'FATAL',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:11 code: '28P01',5ffbe151-47f5-483a-8f25-4b1b9a14d419
2019-01-23 10:33:10NODE_VERSION Value = v8.15.0

**Comment by vkatoch2000** [comment]
DATABASE_URL format is postgres://x_y:z_j_k@x.y-z.e.e.t.z.aws.w-i.net:5432/DBName

username = x_y
password = z_j_k
hostname = x.y-z.e.e.t.z.aws.w-i.net

**Comment by ivarconr** [comment]
It's a bit hard for me to verify, as I'm not allowed to access x.y-z.e.e.t.z.aws.w-i.net. 

Are you able to connect directly with psql? What's the output of?

`psql -h x.y-z.e.e.t.z.aws.w-i.net -d DBName -p 5432 -U x_y -W`

**Comment by vkatoch2000** [comment]
psql (11.1, server 9.5.13)
Type "help" for help.

DEPOSTGRES=#

**Comment by vkatoch2000** [comment]
I tried using script as well
const unleash = require('/usr/lib/node_modules/unleash-server');

unleash
  .start({
    databaseUrl: process.env.DATABASE_URL,
    port: 4242,
    databaseSchema: process.env.SCHEMA
  })
  .then(unleash => {
    console.log(
      `Unleash started on http://localhost:${unleash.app.get('port')}`,
    );
  });

**Comment by vkatoch2000** [comment]
fixed , new line were added there in password
