### ISSUE TITLE
When using database custom schema getting error while startring unleash server , fixed server-impl.js 

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#387]
Unleash started on http://localhost:8080
[2019-01-31T10:44:09.674] [ERROR] client-metrics-store.js - { error: relation "client_metrics" does not exist
    at Connection.parseE (C:\Users\ddd\AppData\Roaming\npm\node_modules\unleash-server\node_modules\pg\lib\connection.js:555:11)
    at Connection.parseMessage (C:\Users\A290434\AppData\Roaming\npm\node_modules\unleash-server\node_modules\pg\lib\connection.js:380:19)
    at Socket.<anonymous> (C:\Users\A290434\AppData\Roaming\npm\node_modules\unleash-server\node_modules\pg\lib\connection.js:120:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
  name: 'error',
  length: 106,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '43',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1160',
  routine: 'parserOpenTable' }
[ERROR] error: relation "client_metrics" does not exist

const unleash = require('unleash-server');

unleash
  .start({
    databaseUrl: 'postgres://ddd:ffffff@localhost:5432/DE',
    port: 8080,
    databaseSchema:'sub',
  })
  .then(unleash => {
    console.log(
       `Unleash started on http://localhost:${unleash.app.get('port')}`,
    );
  });
Its working fine if dont use databaseSchema

**Comment by vkatoch2000** [comment]
its working fine if dont use databaseSchema

**Comment by vkatoch2000** [comment]
I have made changes in method , add databaseSchema agrv in migrator.js , can some body take a look
async function start(opts) {
    const options = createOptions(opts);

    try {
        await migrator({ databaseUrl: options.databaseUrl, databaseSchema: options.databaseSchema  });
    } catch (err) {
        logger.error('Failed to migrate db', err);
        throw err;
    }

    return createApp(options);
}

**Comment by ivarconr** [comment]
Yes, you are right. The current code does not pass it in. Actually passing the full options object to the migrator would solve it. 

```
...
   await migrator(options)
....
````

Afk tonight. Will try to have a fix for this tomorrow.

**Comment by ivarconr** [comment]
Fixed in https://github.com/Unleash/unleash/commit/49a1dc034399b1fb4c433ecac3748534420ca2fc and released as 3.1.6. 

As a bonus I added `databaseSchema' as an optional option to the unleash binary.
