### ISSUE TITLE
Bug Import: yaml type not fully supported

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#411]
When I'm using a regular form-post with a yaml file express reports the file type to be `application/x-yaml` while the [state.js#L25](https://github.com/Unleash/unleash/blob/master/lib/routes/admin-api/state.js#L25) is checking for `text/yaml`.

I also notice that the unleash crashes when this happens:

```
[2019-03-15T16:07:13.823] [INFO] HTTP - 200 POST /api/admin/state/import
application/x-yaml
[ERROR] SyntaxError: Unexpected token e in JSON at position 1
    at JSON.parse (<anonymous>)
    at StateController.import (/home/ivaosthu/code/unleash/unleash/lib/routes/admin-api/state.js:30:29)
    at Layer.handle [as handle_request] (/home/ivaosthu/code/unleash/unleash/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/ivaosthu/code/unleash/unleash/node_modules/express/lib/router/route.js:137:13)
    at Array.<anonymous> (/home/ivaosthu/code/unleash/unleash/node_modules/multer/lib/make-middleware.js:53:37)
    at listener (/home/ivaosthu/code/unleash/unleash/node_modules/on-finished/index.js:169:15)
    at onFinish (/home/ivaosthu/code/unleash/unleash/node_modules/on-finished/index.js:100:5)
    at callback (/home/ivaosthu/code/unleash/unleash/node_modules/ee-first/index.js:55:10)
    at IncomingMessage.onevent (/home/ivaosthu/code/unleash/unleash/node_modules/ee-first/index.js:93:5)
    at emitNone (events.js:111:20)
    at IncomingMessage.emit (events.js:208:7)
    at endReadableNT (_stream_readable.js:1064:12)
    at _combinedTickCallback (internal/process/next_tick.js:139:11)
    at process._tickCallback (internal/process/next_tick.js:181:9)
Program node server.js exited with code 1

Starting child process with 'node server.js'
?
```

/cc @Kouzukii

**Comment by Kouzukii** [comment]
Yep, forgot to move the JSON.parse / YAML.safeLoad into the try/catch. 
I'll open a PR in a minute.
