### ISSUE TITLE
Client_Metrics does not exist when trying to start the server for the first time on kubernetes

### ISSUE THREAD

**Issue by thisisronak** [Unleash/unleash#497]
Stacktrace:

[2019-09-23T11:19:03.378] [INFO] server-impl.js - Unleash has started. { address: '::', family: 'IPv6', port: 4242 }
[2019-09-23T11:19:03.782] [ERROR] client-metrics-store.js - Error fetching metrics last hour { error: relation "client_metrics" does not exist
    at Connection.parseE (/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)
  name: 'error',
  length: 113,
  severity: 'ERROR',
  code: '42P01',
  detail: undefined,
  hint: undefined,
  position: '43',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '1160',
  routine: 'parserOpenTable' }
[ERROR] error: relation "client_metrics" does not exist
    at Connection.parseE (/node_modules/pg/lib/connection.js:602:11)
    at Connection.parseMessage (/node_modules/pg/lib/connection.js:399:19)
    at Socket.<anonymous> (/node_modules/pg/lib/connection.js:121:22)
    at Socket.emit (events.js:198:13)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Socket.Readable.push (_stream_readable.js:224:10)
    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:94:17)

**Comment by ivarconr** [comment]
Are you starting multiple instances at one?
Could it be because the migration is not completed fully?

**Comment by thisisronak** [comment]
Yes I'm indeed starting multiple instances and replicas as well. But I'm not sure how is that a problem?

Furthermore, can you please suggest me via any example on how to pass a custom database schema for kubernetes deployment.

**Comment by ivarconr** [comment]
> But I'm not sure how is that a problem?
It should not in theory, [db-migrate](https://github.com/db-migrate/node-db-migrate) should keep locks if multiple instances tries to run migrations at the same time. 

> Furthermore, can you please suggest me via any example on how to pass a custom database schema for kubernetes deployment.

If you are running unleash [programmatically](https://unleash.github.io/docs/getting_started#2-or-programmatically) you can specify in the `databaseSchema` option.

**Comment by thisisronak** [comment]
As I mentioned earlier, this is a kubernetes deployment and I'm not sure how to pass the custom schema having exhausted most of the options I could think of. 

As of now I have tried passing databaseSchema as DATABASE_SCHEMA env variable without any luck. I have even tried setting the search_path of my postgres db to point to my custom schema instead of default public schema.

Also, looking at the [programmatic](https://unleash.github.io/docs/getting_started#2-or-programmatically) page to provision unleash, I see environment variables defined for other parameters but nothing for databaseSchema.

**Comment by ivarconr** [comment]
You would need to have a custom docker image as there currently is no environment variable for this.

**Comment by thisisronak** [comment]
> Are you able to verify that this does not happen if you only start one instance at a time?

The problem is the same for a single instance. 

I tried using the public postgres schema and it works fine for me. But it fails when I try to use a custom schema
