### ISSUE TITLE
Unstable e2e-tests

### ISSUE THREAD

**Issue by ivarconr** [Unleash/unleash#502]
The last few months e2e test seems to fail 40-50% of the times on travis, but never locally. 

I suspect this might be related to how each e2e-test is setup in ava where the database pool is destroyed in every test in a test file. 

Errors in the logs:
```
[ERROR] Error: Connection terminated
    at Connection.con.once (/home/travis/build/Unleash/unleash/node_modules/pg/lib/client.js:251:9)
    at Object.onceWrapper (events.js:286:20)
    at Connection.emit (events.js:203:15)
    at Socket.<anonymous> (/home/travis/build/Unleash/unleash/node_modules/pg/lib/connection.js:77:10)
    at Socket.emit (events.js:198:13)
    at TCP._handle.close (net.js:606:12)
  ✔ test › e2e › api › admin › feature.e2e › refuses to validate a feature with an existing name (201ms)
  ✖ test/e2e/api/admin/feature.custom-auth.e2e.test.js exited with a non-zero exit code: 1
```

Suggested solution:
Clean up e2e-tests. Setup a db-pool per test-file and destroy the connection only after the completion of all tests. This require some work to make sure each test is NOT depending on data mutated by another test.

**Comment by ivarconr** [comment]
solved via #504
