### ISSUE TITLE
error: permission denied for relation awsdms_ddl_audit while starting unleash

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#567]
2020-03-05 15:57:01[91m[2020-03-05T14:57:01.830] [ERROR] server-impl.js - [39mFailed to migrate db { error: permission denied for relation awsdms_ddl_audit14045c0c-c94f-4eb8-8ed8-136a555be37f
[91m[2020-03-05T14:57:01.830] [ERROR] server-impl.js - [39mFailed to migrate db { error: permission denied for relation awsdms_ddl_audit
2020-03-05 15:57:01 at Connection.parseE (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:614:13)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at Connection.parseMessage (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:413:19)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSSocket.<anonymous> (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:129:22)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at emitOne (events.js:116:13)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSSocket.emit (events.js:211:7)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at addChunk (_stream_readable.js:263:12)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at readableAddChunk (_stream_readable.js:250:11)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSSocket.Readable.push (_stream_readable.js:208:10)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSWrap.onread (net.js:601:20)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 cause: 14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 { error: permission denied for relation awsdms_ddl_audit14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at Connection.parseE (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:614:13)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at Connection.parseMessage (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:413:19)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSSocket.<anonymous> (/usr/lib/node_modules/unleash-server/node_modules/pg/lib/connection.js:129:22)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at emitOne (events.js:116:13)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSSocket.emit (events.js:211:7)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at addChunk (_stream_readable.js:263:12)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at readableAddChunk (_stream_readable.js:250:11)14045c0c-c94f-4eb8-8ed8-136a555be37f
2020-03-05 15:57:01 at TLSSocket.Readable.push (_stream_readable.js:208:10)

**Comment by vkatoch2000** [comment]
Unleash works after disabling the migration code

**Comment by vkatoch2000** [comment]
but still getting error migrate db { error: permission denied for relation awsdms_ddl_audit14045c0c-c94f-4eb8-8ed8-136a555be37f if i enable the migration

**Comment by ivarconr** [comment]
sounds like the user is not allowed to migrate the database anymore. Unleash migrates the database on startup.
