### ISSUE TITLE
Getting error :self signed certificate in certificate chain

### ISSUE THREAD

**Issue by vkatoch2000** [Unleash/unleash#593]
Started getting this error once move to latest version of unleash, any clue ?

2020-05-05 09:14:23Unhandled rejection Error: self signed certificate in certificate chaine88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:23 at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:23 at emitNone (events.js:106:13)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:23 at TLSSocket.emit (events.js:208:7)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:23 at TLSSocket._finishInit (_tls_wrap.js:643:8)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:23 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:14Unhandled rejection Error: self signed certificate in certificate chaine88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:14 at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:14 at emitNone (events.js:106:13)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:14 at TLSSocket.emit (events.js:208:7)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:14 at TLSSocket._finishInit (_tls_wrap.js:643:8)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:14 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:13Unhandled rejection Error: self signed certificate in certificate chaine88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:13 at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:13 at emitNone (events.js:106:13)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:13 at TLSSocket.emit (events.js:208:7)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:13 at TLSSocket._finishInit (_tls_wrap.js:643:8)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:13 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:03Unhandled rejection Error: self signed certificate in certificate chaine88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:03 at TLSSocket.<anonymous> (_tls_wrap.js:1116:38)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:03 at emitNone (events.js:106:13)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:03 at TLSSocket.emit (events.js:208:7)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:03 at TLSSocket._finishInit (_tls_wrap.js:643:8)e88e9490-5ca5-4302-bc82-92261e884db9
2020-05-05 09:14:03 at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:473:38)e88e9490-5ca5-4302-bc82-92261e884db9

**Comment by vkatoch2000** [comment]
I can still able to login to app, there is  no database connectivity it seems

**Comment by ivarconr** [comment]
yes, we are aligning with the specs. This happens because you are using a self-signed SSL certificate. You must either disable SSL, provide the certificate or configure SSL to allow self-signed certificates, see https://node-postgres.com/features/ssl

**Comment by vkatoch2000** [comment]
mean disabling it JDBC connection?
Like we are sending these flags in jdbcc connection URL ssl=true\&sslmode=require

**Comment by vkatoch2000** [comment]
NODE_TLS_REJECT_UNAUTHORIZED='0' ,it works by using this flag
