### ISSUE TITLE
export issue when specifying yaml as in the documentation

### ISSUE THREAD

**Issue by LionH** [Unleash/unleash#615]
I followed the documentation for exporting yaml through the admin api

    http://localhost:33616/api/admin/state/export?format=json&featureToggles=1

but it gives me the following error:

```
[2020-07-30T19:53:35.619] [ERROR] /admin-api/state.js - Server failed executing request YAMLException: unacceptable kind of an object to dump [object Undefined]
    at writeNode (/node_modules/js-yaml/lib/js-yaml/dumper.js:779:13)
    at writeBlockMapping (/node_modules/js-yaml/lib/js-yaml/dumper.js:657:10)
    at writeNode (/node_modules/js-yaml/lib/js-yaml/dumper.js:750:9)
    at dump (/node_modules/js-yaml/lib/js-yaml/dumper.js:840:7)
    at Object.safeDump (/node_modules/js-yaml/lib/js-yaml/dumper.js:846:10)
    at StateController.export (/node_modules/unleash-server/lib/routes/admin-api/state.js:72:44) {
  reason: 'unacceptable kind of an object to dump [object Undefined]',
  mark: undefined
}
```

json export works as expected.

**Comment by ivarconr** [comment]
Thanks. It fails because strategies are set to "undefined".

A workaround for now is to also include strategies

    http://localhost:33616/api/admin/state/export?format=json&featureToggles=1&strategies=1


We will put forward a fix for it soon.
