### ISSUE TITLE
Error: Cannot find module '@hapi/joi'

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [Unleash/unleash#627]
My container now fails to run. It used to work (in May).

```
$ docker logs unleash
internal/modules/cjs/loader.js:965

Error: Cannot find module '@hapi/joi'
Require stack:
- /user.js
- /auth-hook.js
- /index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:965:15)
    at Function.Module._load (internal/modules/cjs/loader.js:841:27)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/user.js:4:13)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
    at Module.load (internal/modules/cjs/loader.js:985:32)
    at Function.Module._load (internal/modules/cjs/loader.js:878:14)
    at Module.require (internal/modules/cjs/loader.js:1025:19)
```

My `index.js` file is:
```
'use strict';

const unleash = require('unleash-server');
const myCustomAdminAuth = require('./auth-hook.js');

let options = { adminAuthentication: 'custom', preRouterHook: myCustomAdminAuth };

unleash.start(options);
```

The only time I see `Joi` referenced is in my `User.js`:

```
'use strict';

const gravatarUrl = require('gravatar-url');
const Joi = require('@hapi/joi');

module.exports = class User {
    constructor({
        name,
        email,
        username,
        systemId,
        imageUrl,
        permissions,
    } = {}) {
        if (!username && !email) {
            throw new TypeError('Username or Email us reuqired');
        }
        Joi.assert(email, Joi.string().email(), 'Email');
        Joi.assert(username, Joi.string(), 'Username');
        Joi.assert(name, Joi.string(), 'Name');

        this.name = name;
        this.username = username;
        this.email = email;
        this.systemId = systemId;
        this.permissions = permissions;
        this.imageUrl = imageUrl || this.generateImageUrl();
    }

    generateImageUrl() {
        return gravatarUrl(this.email || this.username, {
            size: '42',
            default: 'retro',
        });
    }
};
``

**Comment by Dynatrace-Adam-Gardner** [comment]
Fixed: Change `const Joi = require('@hapi/joi');` to `const Joi = require('joi');`

See https://github.com/sideway/joi/issues/2411
