### ISSUE TITLE
 Failed to migrate db error: current transaction is aborted, commands ignored until end of transaction bloc

### ISSUE THREAD

**Issue by parraletz** [Unleash/unleash#853]
Unleash services not starting:

`node server.js
`
**[ERROR] 20210428103923-onboard-projects-to-rbac error: current transaction is aborted, commands ignored until end of transaction block**

Env:

Docker and instance alone

LOG:

[ERROR] 20210428103923-onboard-projects-to-rbac error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/ec2-user/pkg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 145,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1363',
  routine: 'exec_parse_message'
}
[2021-05-25T20:17:24.436] [ERROR] server-impl.js - Failed to migrate db error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/ec2-user/pkg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
  length: 145,
  severity: 'ERROR',
  code: '25P02',
  detail: undefined,
  hint: undefined,
  position: undefined,
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'postgres.c',
  line: '1363',
  routine: 'exec_parse_message'
}
[ERROR] error: current transaction is aborted, commands ignored until end of transaction block
    at Parser.parseErrorMessage (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:287:98)
    at Parser.handlePacket (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:126:29)
    at Parser.parse (/home/ec2-user/pkg/node_modules/pg-protocol/dist/parser.js:39:38)
    at Socket.<anonymous> (/home/ec2-user/pkg/node_modules/pg-protocol/dist/index.js:11:42)
    at Socket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)`
`

**Comment by ivarconr** [comment]
Hi, thanks for reporting. 

which version of Unleash are you coming from and whats the new version you are trying to start? 

To me it seems like it has not loaded database details properly, based to the stack trace: 

```
internalQuery: undefined,
where: undefined,
schema: undefined,
table: undefined,
column: undefined,
dataType: undefined,
constraint: undefined,
file: 'postgres.c',
line: '1363',
```

How are you providing database options?

**Comment by ivarconr** [comment]
closed due to inactivity. please re-open if you can provide additional details.
